application: cacophon-demo
runtime: custom
module: frontend-nodejs
version: 1
api_version: 1
vm: true

manual_scaling:
  instances: 1

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index\.html

- url: /js
  static_dir: dist/js

- url: /img
  static_dir: dist/img

- url: /favicon\.ico
  static_files: dist/favicon.ico
  upload: dist/favicon\.ico

- url: /robots\.txt
  static_files: dist/robots.txt
  upload: dist/robots\.text

- url: /.*
  script: server.js

